config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root   "static_pages#home"
    post  "/inquiry", to: "static_pages#inquiry"

=begin
  get    "/help",    to: "static_pages#help"
  get    "/about",   to: "static_pages#about"
  get    "/contact", to: "static_pages#contact"
  get    "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  get '/microposts', to: 'static_pages#home'
=end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @is_black = true
    @bulletins = Bulletin.all.order(announcement_date: :desc)
  end

  def inquiry
    text = <<~EOS
      お問い合わせがありました。
      ```
      要件： #{params[:inquiry_type]}
      お名前: #{params[:name]}
      会社名： #{params[:company]}
      メールアドレス: #{params[:email]}
      電話番号： #{params[:phone]}
      お問い合わせ内容:
      #{params[:message]}
      ```
    EOS
    notifier = Slack::Notifier.new(
      ENV['WEBHOOK_URL'],
      channel: '#company_inquiry',
      username: params[:inquiry_type],
    )
    notifier.post(text: text,
                  icon_url: DIQT_ICON)
    flash[:success] = 'お問い合わせを受け付けました。'
    redirect_to root_path
  end

  def help ;end

  def about ;end

  def contact ;end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/lp/_company.html.erb
<div class="px-4" id="company-page">
  <div class="w-100 d-block py-5"></div>
  <!--
  <h1 class="top-heading pt-5 text-white text-center mb-3 fw-bold"> <#%= t('layouts.company') %></h1>
  -->
</div>

<div class="row mt-5 px-4 justify-content-md-center">
  <div class="col-xl-8">
    <h1 class="top-heading pt-5 text-white text-left">
      <%= t('layouts.company') %>
    </h1>

    <table class="table background-black no-top-border">
      <tbody>
      <tr class="">
        <th scope="row"><%= t('static_pages.company') %></th>
        <td><%= t('shared.company.name') %></td>
      </tr>
      <tr>
        <th scope="row"><%= t('static_pages.address') %></th>
        <td><%= t('shared.company.address') %></td>
      </tr>
      <tr>
        <th scope="row"><%= t('static_pages.ceo') %></th>
        <td><%= t('static_pages.ceo_name') %></td>
      </tr>
      <tr>
        <th scope="row"><%= t('static_pages.email') %></th>
        <td><%= t('shared.company.email') %></td>
      </tr>
      <tr>
        <th scope="row"><%= t('static_pages.phone') %></th>
        <td><%= t('shared.company.phone') %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row mt-5 px-4 justify-content-md-center">
  <div class="col-xl-8">
    <div class="row">
      <div class="mt-5 col-xl-2 col-5">
        <img src="<%= "https://cdn.startupleague.jp/ict/2305/image/profile.jpg" %>" class="img-fluid pe-3 rounded-circle" alt="">
      </div>
      <div class="col-xl-10">
        <h3 class="text-white text-left">
          <%= t('static_pages.ceo_name') %>
        </h3>
        <div class="text-light">
          <p>高校在学中に週刊少年ジャンプで<a href="https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%88%E3%82%AD%E3%83%B3%E7%82%8E#:~:text=%E5%8F%97%E8%B3%9E%E4%B8%80%E8%A6%A7,-%E5%9B%9E&text=%E3%83%BB%E7%82%8E%E5%8A%AA%E5%8A%9B%E8%B3%9E%20%2D%20%E9%99%BD%E5%9C%B0,%E5%B2%A1%E6%9C%AC%E5%81%A5%E5%A4%AA%E9%83%8E%E3%80%8CMerry%20Crisis!%E3%80%8D&text=%E3%83%BB%E6%BA%96%E3%80%85%E3%83%97%E3%83%AA%E3%83%B3%E3%82%B9%20%2D%20%E6%A1%91%E9%87%8E%E5%9C%AD%E8%BC%9D,%E7%9B%B8%E5%B7%9D%E7%9C%9F%E5%8F%B8%E3%80%8C%E3%83%90%E3%83%83%E3%83%89%E3%82%A8%E3%83%B3%E3%83%89%E3%82%AF%E3%83%A9%E3%83%83%E3%82%B7%E3%83%A5!!%E3%80%8D" target='_blank' rel="noopener" class="link-light">漫画賞</a>を受賞。
            卒業後、業務用システムの開発を請け負う株式会社ティーワイシーに就職。
            2019年に株式会社BooQs設立し、自身がエンジニアとして英語の技術ドキュメントと格闘する中で痛感した英語の語彙習得と忘却の課題を解決するために「忘れない辞書＆単語帳アプリ」としてDiQt（ディクト）を開発し、Web版・モバイルアプリ版・Chrome拡張版をリリースする。2022年度総務省主催異能vationプログラム「ジェネレーションアワード」ノミネート。</p>
        </div>

        <div class="d-flex flex-row mb-3">
          <%= link_to 'https://note.com/kawanjin01',
                      class: 'btn btn-outline-light btn-sm mt-3', target: '_blank', rel: 'noopener' do %>
            Note <i class="far fa-external-link ms-2"></i>
          <% end %>

          <%= link_to 'https://twitter.com/kawanji01',
                      class: 'btn btn-outline-light btn-sm mt-3 ms-3', target: '_blank', rel: 'noopener' do %>
            X <i class="far fa-external-link ms-2"></i>
          <% end %>

          <%= link_to 'https://www.facebook.com/kawanji01',
                      class: 'btn btn-outline-light btn-sm mt-3 ms-3', target: '_blank', rel: 'noopener' do %>
            Facebook <i class="far fa-external-link ms-2"></i>
          <% end %>

          <%= link_to 'https://github.com/kawanji01',
                      class: 'btn btn-outline-light btn-sm mt-3 ms-3', target: '_blank', rel: 'noopener' do %>
            GitHub <i class="far fa-external-link ms-2"></i>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>



<div class="row mt-5 px-4 justify-content-md-center">
  <div class="col-xl-8">
    <h3 class="pt-5 text-white text-left">
      <%= t('lp.history') %>
    </h3>
    <div class="text-light mt-4">
      <p>・2019年2月19日創業</p>
      <p>・2022年総務省主催異能ベーションプログラム「ジェネレーションアワード」ノミネート</p>
      <p>・2023年Microsoft for Startupプログラムに採択</p>
      <p>・2023年総務省の主催するICTスタートアップリーグプログラムに採択</p>
    </div>
  </div>
</div>

app/views/static_pages/lp/_contact.html.erb
<div class="px-4" id="contact-page">
  <div class="w-100 d-block py-5"></div>
  <!--
  <h1 class="top-heading pt-5 text-white text-center mb-3 fw-bold"> <#%= t('layouts.company') %></h1>
  -->
</div>


<div class="row mt-5 px-4 justify-content-md-center">
  <div class="col-xl-8">
    <h1 class="top-heading pt-5 text-white text-left">
      <%= t('layouts.contact') %>
    </h1>
    <div class="px-3">
      <%= form_with url: inquiry_path, method: :post, local: true, class: 'mt-5' do |f| %>

        <%= f.label :name, t('lp.name'), class: "text-left small text-white" %>
        <%= f.text_field :name, class: "form-control mb-4", placeholder: t('lp.name_placeholder'), required: true %>

        <%= f.label :company, "#{t('lp.company_name')}（#{t('lp.optional')}）", class: "text-left small text-white" %>
        <%= f.text_field :company, class: "form-control mb-4", placeholder: t('lp.company_name_placeholder') %>

        <%= f.label :email, t('static_pages.email'), class: "text-left small text-white" %>
        <%= f.email_field :email, class: "form-control mb-4", placeholder: t('static_pages.email'), required: true %>

        <%= f.label :phone, t('static_pages.phone'), class: "text-left small text-white" %>
        <%= f.text_field :phone, class: "form-control mb-4", placeholder: t('static_pages.phone'), required: true %>

        <%= f.label :inquiry_type, t('lp.inquiry_type'), class: "text-left small text-white" %>
        <%= f.select :inquiry_type, [[t('lp.about_apps'), t('lp.about_apps')], [t('lp.others'), t('lp.others')], [t('lp.about_sales'), t('lp.about_sales')],], {}, { class: 'form-control mb-4' } %>

        <%= f.label :message, t('lp.inquiry_content'), class: "text-left small text-white" %>
        <%= f.text_area :message, class: "form-control mb-4", placeholder: t('lp.inquiry_content'), rows: 4, required: true %>

        <%= f.submit t('lp.inquire'), class: "btn btn-success btn-light-green w-100 rounded-pill modal-show-signup fw-bold mt-4", data: { disable_with: '送信中...' } %>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/lp/_home.html.erb
<div class="px-4">
  <div class="w-100 d-block py-5"></div>
  <h1 class="top-heading pt-5 text-white text-center mb-3 fw-bold" id="home-page"><%= t('shared.company.name') %></h1>
</div>

<div class="w-100 d-block py-5"></div>
<!-- First START -->
<div class="row mt-5 px-4">
  <div class="col-xl-6">
    <h1 class="top-heading pt-5 text-white text-left lh-base">
      <%= t('lp.first_title_html') %>
    </h1>
    <div class="text-light mb-4">
      <%= t('lp.first_description_html') %>
    </div>

    <%= link_to 'https://note.com/kawanjin01', target: '_blank', rel: 'noopener' do %>
      <div class="btn btn btn-success rounded-pill fw-bold w-100 my-5">
        <%= t('lp.blog') %>
      </div>
    <% end %>
  </div>

  <div class="col-xl-6 mb-5">
    <img src="<%= "https://tuflingual.s3.ap-northeast-1.amazonaws.com/assets/lp/undraw_connected_world_wuay.svg" %>" class="img-fluid" alt="">
  </div>
</div>

app/views/static_pages/lp/_news.html.erb
<div class="px-4" id="news-page">
  <div class="w-100 d-block py-5"></div>
  <!--
  <h1 class="top-heading pt-5 text-white text-center mb-3 fw-bold"> <#%= t('layouts.company') %></h1>
  -->
</div>
<div class="row mt-5 px-4 justify-content-md-center">
  <div class="col-xl-8">
    <h1 class="top-heading pt-5 text-white text-left">
      <%= t('layouts.news') %>
    </h1>

    <% @bulletins.each do |bulletin| %>

      <div class="my-4 text-white bulletin-<%= bulletin.id %>">
        <p>
          ・<%= bulletin.announcement_date.strftime("%Y年%m月%d日") %> :
          <% if bulletin.url.present? %>
            <%= link_to bulletin.title, bulletin.url, target: '_blank', rel: 'noopener', class: 'link-light link-offset-2 link-underline' %>
          <% else %>
            <%= bulletin.title %>
          <% end %>
        </p>

      </div>
    <% end %>

  </div>
</div>

app/views/static_pages/lp/_services.html.erb
<div class="px-4" id="services-page">
  <div class="w-100 d-block py-5"></div>
  <!--
  <h1 class="top-heading pt-5 text-white text-center mb-3 fw-bold" id="services"> <#%= t('layouts.services') %></h1>
  -->
</div>

<div class="row mt-5 px-4">
  <div class="col-xl-6">
    <h1 class="top-heading pt-5 text-white text-left lh-base">
      <%= t('lp.second_title_html') %>
    </h1>
    <div class="text-light mb-4">
      <%= t('lp.second_description_html') %>
    </div>

    <%= link_to "https://www.diqt.net/#{@locale}", target: '_blank', rel: 'noopener' do %>
      <div class="btn btn btn-success rounded-pill fw-bold w-100 my-4">
        <i class="far fa-browser me-2"></i><%= t('lp.web_app') %>
      </div>
    <% end %>

    <%= link_to 'https://apps.apple.com/jp/app/%E5%BF%98%E3%82%8C%E3%81%AA%E3%81%84%E8%BE%9E%E6%9B%B8-%E5%8D%98%E8%AA%9E%E5%B8%B3-%E3%83%87%E3%82%A3%E3%82%AF%E3%83%88/id1594559036?uo=4', target: '_blank', rel: 'noopener' do %>
      <div class="btn btn btn-success rounded-pill fw-bold w-100 my-4">
        <i class="fab fa-apple me-2"></i><%= t('lp.ios_app') %>
      </div>
    <% end %>

    <%= link_to 'https://play.google.com/store/apps/details?id=com.booqs.booqs_mobile&hl=ja', target: '_blank', rel: 'noopener' do %>
      <div class="btn btn btn-success rounded-pill fw-bold w-100 my-4">
        <i class="fab fa-android me-2"></i><%= t('lp.android_app') %>
      </div>
    <% end %>

    <%= link_to 'https://chromewebstore.google.com/detail/%E8%AA%BF%E3%81%B9%E3%81%9F%E3%82%89%E5%BF%98%E3%82%8C%E3%81%AA%E3%81%84%E8%BE%9E%E6%9B%B8-%E3%83%87%E3%82%A3%E3%82%AF%E3%83%88/khgjdchimekphdebkmcknjkphkbpbpkj?hl=ja&authuser=0', target: '_blank', rel: 'noopener' do %>
      <div class="btn btn btn-success rounded-pill fw-bold w-100 my-4">
        <i class="fab fa-chrome me-2"></i><%= t('lp.chrome_extension') %>
      </div>
    <% end %>

  </div>

  <div class="col-xl-6 mb-5">
    <img src="<%= "https://diqt.s3.ap-northeast-1.amazonaws.com/assets/images/lp/lp_mockup_1_#{@locale}.png" %>" class="img-fluid" alt="">
  </div>

</div>